name: cbba_mobility
services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    volumes:
      - ./otel-collector.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - "4317:4317"
    depends_on:
      - tempo
      - loki

  tempo:
    # latest uses kafka and there is no reliable way to disable it yet
    image: grafana/tempo:2.6.1
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
      - tempo_data:/var/tempo

  loki:
    image: grafana/loki:latest
    volumes:
      - loki_data:/loki

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    depends_on:
      - otel-collector

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
    depends_on:
      - tempo
      - loki
      - prometheus

  valhalla:
    image: ghcr.io/gis-ops/docker-valhalla/valhalla:latest
    ports:
      - "8002:8002"
    volumes:
      - valhalla_data:/custom_files
    environment:
      tile_urls: https://download.geofabrik.de/south-america/bolivia-latest.osm.pbf
      serve_tiles: "True"
      build_elevation: "False"
      build_admins: "False"
      build_time_zones: "False"

volumes:
  tempo_data:
  loki_data:
  prometheus_data:
  grafana_data:
  valhalla_data: