"""remove routes table

Revision ID: 0775b27e0935
Revises: 9bf8685c237f
Create Date: 2026-02-22 12:24:10.167105

"""

from typing import Sequence, Union

import geoalchemy2
import sqlalchemy as sa
from alembic import op
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision: str = "0775b27e0935"
down_revision: Union[str, None] = "9bf8685c237f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_geospatial_column(
        "lines",
        sa.Column(
            "path",
            Geometry(
                geometry_type="LINESTRING",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
    )
    op.create_geospatial_index("idx_lines_path", "lines", ["path"], unique=False, postgresql_using="gist", postgresql_ops={})
    op.alter_column("recording_sessions", "line_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("recording_sessions", "line_id", existing_type=sa.INTEGER(), nullable=False)
    op.drop_geospatial_index("idx_lines_path", table_name="lines", postgresql_using="gist", column_name="path")
    op.drop_geospatial_column("lines", "path")
    # ### end Alembic commands ###
