"""initial

Revision ID: 1a0e9e4ac5e0
Revises: 
Create Date: 2026-04-20 06:26:38.995187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from geoalchemy2 import Geometry
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '1a0e9e4ac5e0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Ensure PostGIS extension is available
    op.execute('CREATE EXTENSION IF NOT EXISTS postgis')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lines',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'MERGED', name='linestatus'), nullable=False),
    sa.Column('merged_into_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['merged_into_id'], ['lines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lines_name'), 'lines', ['name'], unique=False)
    op.create_table('line_votes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('line_id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('vote', sa.Enum('APPROVE', 'REJECT', name='votechoice'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['line_id'], ['lines.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('line_id', 'device_id', name='uq_line_vote_device')
    )
    op.create_index(op.f('ix_line_votes_device_id'), 'line_votes', ['device_id'], unique=False)
    op.create_index(op.f('ix_line_votes_line_id'), 'line_votes', ['line_id'], unique=False)
    op.create_table('routes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('line_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('COMPUTED', 'IMPORTED', name='routesource'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'SUPERSEDED', name='routestatus'), nullable=False),
    sa.Column('trip_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['line_id'], ['lines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routes_line_id'), 'routes', ['line_id'], unique=False)
    op.create_geospatial_table('trip_sessions',
    sa.Column('line_id', sa.Uuid(), nullable=True),
    sa.Column('direction', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('device_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('device_model', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('os_version', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'ABANDONED', 'DISCARDED', name='sessionstatus'), nullable=False),
    sa.Column('processing_status', sa.Enum('RAW', 'PROCESSING', 'PROCESSED', 'FAILED', name='processingstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(), nullable=False),
    sa.Column('computed_path', Geometry(geometry_type='LINESTRING', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.ForeignKeyConstraint(['line_id'], ['lines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_trip_sessions_computed_path', 'trip_sessions', ['computed_path'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_trip_sessions_device_id'), 'trip_sessions', ['device_id'], unique=False)
    op.create_index(op.f('ix_trip_sessions_line_id'), 'trip_sessions', ['line_id'], unique=False)
    op.create_geospatial_table('detours',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('line_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'EXPIRED', name='detourstatus'), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('path', Geometry(geometry_type='LINESTRING', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_confirmed_at', sa.DateTime(), nullable=False),
    sa.Column('confirmed_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['line_id'], ['lines.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['trip_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_detours_path', 'detours', ['path'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_detours_line_id'), 'detours', ['line_id'], unique=False)
    op.create_index(op.f('ix_detours_session_id'), 'detours', ['session_id'], unique=False)
    op.create_geospatial_table('route_edges',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('route_id', sa.Uuid(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('valhalla_edge_id', sa.BigInteger(), nullable=True),
    sa.Column('forward', sa.Boolean(), nullable=False),
    sa.Column('path', Geometry(geometry_type='LINESTRING', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', name='edgestatus'), nullable=False),
    sa.Column('votes_for', sa.Integer(), nullable=False),
    sa.Column('votes_against', sa.Integer(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_route_edges_path', 'route_edges', ['path'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_route_edges_route_id'), 'route_edges', ['route_id'], unique=False)
    op.create_table('trip_sensor_readings',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('accel_x', sa.Float(), nullable=True),
    sa.Column('accel_y', sa.Float(), nullable=True),
    sa.Column('accel_z', sa.Float(), nullable=True),
    sa.Column('gyro_x', sa.Float(), nullable=True),
    sa.Column('gyro_y', sa.Float(), nullable=True),
    sa.Column('gyro_z', sa.Float(), nullable=True),
    sa.Column('pressure', sa.Float(), nullable=True),
    sa.Column('magnetic_heading', sa.Float(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['trip_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trip_sensor_readings_session_id'), 'trip_sensor_readings', ['session_id'], unique=False)
    op.create_geospatial_table('trip_session_points',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('altitude', sa.Float(), nullable=True),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('bearing', sa.Float(), nullable=True),
    sa.Column('horizontal_accuracy', sa.Float(), nullable=True),
    sa.Column('vertical_accuracy', sa.Float(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('point', Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['trip_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_trip_session_points_point', 'trip_session_points', ['point'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_trip_session_points_session_id'), 'trip_session_points', ['session_id'], unique=False)
    op.create_geospatial_table('trips',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('line_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('CLEAN', 'DEVIATED', name='tripstatus'), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('frechet_distance', sa.Float(), nullable=True),
    sa.Column('computed_path', Geometry(geometry_type='LINESTRING', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['line_id'], ['lines.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['trip_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_trips_computed_path', 'trips', ['computed_path'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_trips_line_id'), 'trips', ['line_id'], unique=False)
    op.create_index(op.f('ix_trips_session_id'), 'trips', ['session_id'], unique=False)
    op.create_table('edge_votes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('edge_id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('vote', sa.Enum('APPROVE', 'REJECT', name='votechoice'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['edge_id'], ['route_edges.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('edge_id', 'device_id', name='uq_edge_vote_device')
    )
    op.create_index(op.f('ix_edge_votes_device_id'), 'edge_votes', ['device_id'], unique=False)
    op.create_index(op.f('ix_edge_votes_edge_id'), 'edge_votes', ['edge_id'], unique=False)
    op.create_table('resampled_trips',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('trip_id', sa.Uuid(), nullable=False),
    sa.Column('interval_meters', sa.Float(), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('point_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resampled_trips_trip_id'), 'resampled_trips', ['trip_id'], unique=False)
    op.create_table('travel_time_samples',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('trip_id', sa.Uuid(), nullable=False),
    sa.Column('edge_id', sa.Uuid(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('hour_of_day', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['edge_id'], ['route_edges.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_travel_time_samples_edge_id'), 'travel_time_samples', ['edge_id'], unique=False)
    op.create_index(op.f('ix_travel_time_samples_trip_id'), 'travel_time_samples', ['trip_id'], unique=False)
    op.create_table('trip_matched_edges',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('trip_id', sa.Uuid(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('valhalla_edge_id', sa.BigInteger(), nullable=False),
    sa.Column('forward', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trip_id', 'sequence', name='uq_trip_matched_edges_trip_sequence')
    )
    op.create_index(op.f('ix_trip_matched_edges_trip_id'), 'trip_matched_edges', ['trip_id'], unique=False)
    op.create_index('ix_trip_matched_edges_valhalla_edge_id_forward', 'trip_matched_edges', ['valhalla_edge_id', 'forward'], unique=False)
    op.create_geospatial_table('trip_points',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('trip_id', sa.Uuid(), nullable=False),
    sa.Column('point_index', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('point', Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_trip_points_point', 'trip_points', ['point'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_trip_points_trip_id'), 'trip_points', ['trip_id'], unique=False)
    op.create_geospatial_table('resampled_trip_points',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('resampled_trip_id', sa.Uuid(), nullable=False),
    sa.Column('point_index', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('point', Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.ForeignKeyConstraint(['resampled_trip_id'], ['resampled_trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_resampled_trip_points_point', 'resampled_trip_points', ['point'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_resampled_trip_points_resampled_trip_id'), 'resampled_trip_points', ['resampled_trip_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resampled_trip_points_resampled_trip_id'), table_name='resampled_trip_points')
    op.drop_geospatial_index('idx_resampled_trip_points_point', table_name='resampled_trip_points', postgresql_using='gist', column_name='point')
    op.drop_geospatial_table('resampled_trip_points')
    op.drop_index(op.f('ix_trip_points_trip_id'), table_name='trip_points')
    op.drop_geospatial_index('idx_trip_points_point', table_name='trip_points', postgresql_using='gist', column_name='point')
    op.drop_geospatial_table('trip_points')
    op.drop_index('ix_trip_matched_edges_valhalla_edge_id_forward', table_name='trip_matched_edges')
    op.drop_index(op.f('ix_trip_matched_edges_trip_id'), table_name='trip_matched_edges')
    op.drop_table('trip_matched_edges')
    op.drop_index(op.f('ix_travel_time_samples_trip_id'), table_name='travel_time_samples')
    op.drop_index(op.f('ix_travel_time_samples_edge_id'), table_name='travel_time_samples')
    op.drop_table('travel_time_samples')
    op.drop_index(op.f('ix_resampled_trips_trip_id'), table_name='resampled_trips')
    op.drop_table('resampled_trips')
    op.drop_index(op.f('ix_edge_votes_edge_id'), table_name='edge_votes')
    op.drop_index(op.f('ix_edge_votes_device_id'), table_name='edge_votes')
    op.drop_table('edge_votes')
    op.drop_index(op.f('ix_trips_session_id'), table_name='trips')
    op.drop_index(op.f('ix_trips_line_id'), table_name='trips')
    op.drop_geospatial_index('idx_trips_computed_path', table_name='trips', postgresql_using='gist', column_name='computed_path')
    op.drop_geospatial_table('trips')
    op.drop_index(op.f('ix_trip_session_points_session_id'), table_name='trip_session_points')
    op.drop_geospatial_index('idx_trip_session_points_point', table_name='trip_session_points', postgresql_using='gist', column_name='point')
    op.drop_geospatial_table('trip_session_points')
    op.drop_index(op.f('ix_trip_sensor_readings_session_id'), table_name='trip_sensor_readings')
    op.drop_table('trip_sensor_readings')
    op.drop_index(op.f('ix_route_edges_route_id'), table_name='route_edges')
    op.drop_geospatial_index('idx_route_edges_path', table_name='route_edges', postgresql_using='gist', column_name='path')
    op.drop_geospatial_table('route_edges')
    op.drop_index(op.f('ix_detours_session_id'), table_name='detours')
    op.drop_index(op.f('ix_detours_line_id'), table_name='detours')
    op.drop_geospatial_index('idx_detours_path', table_name='detours', postgresql_using='gist', column_name='path')
    op.drop_geospatial_table('detours')
    op.drop_index(op.f('ix_trip_sessions_line_id'), table_name='trip_sessions')
    op.drop_index(op.f('ix_trip_sessions_device_id'), table_name='trip_sessions')
    op.drop_geospatial_index('idx_trip_sessions_computed_path', table_name='trip_sessions', postgresql_using='gist', column_name='computed_path')
    op.drop_geospatial_table('trip_sessions')
    op.drop_index(op.f('ix_routes_line_id'), table_name='routes')
    op.drop_table('routes')
    op.drop_index(op.f('ix_line_votes_line_id'), table_name='line_votes')
    op.drop_index(op.f('ix_line_votes_device_id'), table_name='line_votes')
    op.drop_table('line_votes')
    op.drop_index(op.f('ix_lines_name'), table_name='lines')
    op.drop_table('lines')

    op.execute('DROP TYPE IF EXISTS linestatus')
    op.execute('DROP TYPE IF EXISTS estimationstatus')
    op.execute('DROP TYPE IF EXISTS sessionstatus')
    op.execute('DROP TYPE IF EXISTS processingstatus')
    op.execute('DROP TYPE IF EXISTS segmentstatus')
    op.execute('DROP TYPE IF EXISTS tripstatus')
    op.execute('DROP TYPE IF EXISTS votechoice')
    # ### end Alembic commands ###
