"""add line_votes table

Revision ID: 5628a7215c35
Revises: b26a3efa8d68
Create Date: 2026-04-08 02:32:35.832551

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel.sql.sqltypes
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '5628a7215c35'
down_revision: Union[str, None] = 'b26a3efa8d68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('line_votes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('line_id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('vote', postgresql.ENUM('APPROVE', 'REJECT', name='votechoice', create_type=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['line_id'], ['lines.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('line_id', 'device_id', name='uq_line_vote_device')
    )
    op.create_index(op.f('ix_line_votes_device_id'), 'line_votes', ['device_id'], unique=False)
    op.create_index(op.f('ix_line_votes_line_id'), 'line_votes', ['line_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_line_votes_line_id'), table_name='line_votes')
    op.drop_index(op.f('ix_line_votes_device_id'), table_name='line_votes')
    op.drop_table('line_votes')
    # ### end Alembic commands ###
