"""add pipeline run tracking tables

Revision ID: 5dbc73772968
Revises: c4d5e6f7a8b9
Create Date: 2026-05-01 14:39:52.815834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5dbc73772968'
down_revision: Union[str, None] = 'c4d5e6f7a8b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('trigger', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('status', sa.Enum('RUNNING', 'COMPLETED', 'FAILED', name='pipelinerunstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pipeline_step_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('step_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'SKIPPED', name='stepstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['pipeline_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_step_results_run_id'), 'pipeline_step_results', ['run_id'], unique=False)
    op.drop_constraint(op.f('uq_fare_zones_name'), 'fare_zones', type_='unique')
    op.drop_index(op.f('ix_fare_zones_name'), table_name='fare_zones')
    op.create_index(op.f('ix_fare_zones_name'), 'fare_zones', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fare_zones_name'), table_name='fare_zones')
    op.create_index(op.f('ix_fare_zones_name'), 'fare_zones', ['name'], unique=False)
    op.create_unique_constraint(op.f('uq_fare_zones_name'), 'fare_zones', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_pipeline_step_results_run_id'), table_name='pipeline_step_results')
    op.drop_table('pipeline_step_results')
    op.drop_table('pipeline_runs')
    # ### end Alembic commands ###
