"""add detours table

Revision ID: 61da4fa0acf9
Revises: 5628a7215c35
Create Date: 2026-04-10 15:25:38.397611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import geoalchemy2
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision: str = '61da4fa0acf9'
down_revision: Union[str, None] = '5628a7215c35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_geospatial_table('detours',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('line_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'EXPIRED', name='detourstatus'), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('path', Geometry(geometry_type='LINESTRING', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_confirmed_at', sa.DateTime(), nullable=False),
    sa.Column('confirmed_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['line_id'], ['lines.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['trip_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_detours_path', 'detours', ['path'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_detours_line_id'), 'detours', ['line_id'], unique=False)
    op.create_index(op.f('ix_detours_session_id'), 'detours', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_detours_session_id'), table_name='detours')
    op.drop_index(op.f('ix_detours_line_id'), table_name='detours')
    op.drop_geospatial_index('idx_detours_path', table_name='detours', postgresql_using='gist', column_name='path')
    op.drop_geospatial_table('detours')
    # ### end Alembic commands ###
