"""initial

Revision ID: 9bf8685c237f
Revises:
Create Date: 2026-02-02 20:34:39.423546

"""

from typing import Sequence, Union

import geoalchemy2
import sqlalchemy as sa
from alembic import op
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision: str = "9bf8685c237f"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("username", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "lines",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("status", sa.Enum("PENDING", "APPROVED", "MERGED", name="linestatus"), nullable=False),
        sa.Column("submitted_by_id", sa.Integer(), nullable=True),
        sa.Column("merged_into_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["merged_into_id"], ["lines.id"]),
        sa.ForeignKeyConstraint(["submitted_by_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_lines_name"), "lines", ["name"], unique=False)
    op.create_index(op.f("ix_lines_submitted_by_id"), "lines", ["submitted_by_id"], unique=False)
    op.create_geospatial_table(
        "recording_sessions",
        sa.Column("line_id", sa.Integer(), nullable=False),
        sa.Column("direction", sa.String(length=100), nullable=True),
        sa.Column("device_model", sa.String(length=100), nullable=True),
        sa.Column("os_version", sa.String(length=50), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("IN_PROGRESS", "COMPLETED", "CANCELLED", "ABANDONED", name="recordingstatus"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("ended_at", sa.DateTime(), nullable=True),
        sa.Column("last_activity_at", sa.DateTime(), nullable=False),
        sa.Column(
            "computed_path",
            Geometry(
                geometry_type="LINESTRING",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["line_id"], ["lines.id"]),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_geospatial_index(
        "idx_recording_sessions_computed_path",
        "recording_sessions",
        ["computed_path"],
        unique=False,
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_index(op.f("ix_recording_sessions_line_id"), "recording_sessions", ["line_id"], unique=False)
    op.create_index(op.f("ix_recording_sessions_user_id"), "recording_sessions", ["user_id"], unique=False)
    op.create_geospatial_table(
        "routes",
        sa.Column("direction", sa.String(length=100), nullable=False),
        sa.Column("distinctive", sa.String(length=255), nullable=True),
        sa.Column("color", sa.String(length=7), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("line_id", sa.Integer(), nullable=False),
        sa.Column(
            "path",
            Geometry(
                geometry_type="LINESTRING",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["line_id"], ["lines.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_geospatial_index(
        "idx_routes_path",
        "routes",
        ["path"],
        unique=False,
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_index(op.f("ix_routes_line_id"), "routes", ["line_id"], unique=False)
    op.create_geospatial_table(
        "location_points",
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column("altitude", sa.Float(), nullable=True),
        sa.Column("speed", sa.Float(), nullable=True),
        sa.Column("bearing", sa.Float(), nullable=True),
        sa.Column("horizontal_accuracy", sa.Float(), nullable=True),
        sa.Column("vertical_accuracy", sa.Float(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column(
            "point",
            Geometry(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["session_id"], ["recording_sessions.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_geospatial_index(
        "idx_location_points_point",
        "location_points",
        ["point"],
        unique=False,
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_index(op.f("ix_location_points_session_id"), "location_points", ["session_id"], unique=False)
    op.create_table(
        "sensor_readings",
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("accel_x", sa.Float(), nullable=True),
        sa.Column("accel_y", sa.Float(), nullable=True),
        sa.Column("accel_z", sa.Float(), nullable=True),
        sa.Column("gyro_x", sa.Float(), nullable=True),
        sa.Column("gyro_y", sa.Float(), nullable=True),
        sa.Column("gyro_z", sa.Float(), nullable=True),
        sa.Column("pressure", sa.Float(), nullable=True),
        sa.Column("magnetic_heading", sa.Float(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["session_id"], ["recording_sessions.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sensor_readings_session_id"), "sensor_readings", ["session_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sensor_readings_session_id"), table_name="sensor_readings")
    op.drop_table("sensor_readings")
    op.drop_index(op.f("ix_location_points_session_id"), table_name="location_points")
    op.drop_geospatial_index(
        "idx_location_points_point",
        table_name="location_points",
        postgresql_using="gist",
        column_name="point",
    )
    op.drop_geospatial_table("location_points")
    op.drop_index(op.f("ix_routes_line_id"), table_name="routes")
    op.drop_geospatial_index("idx_routes_path", table_name="routes", postgresql_using="gist", column_name="path")
    op.drop_geospatial_table("routes")
    op.drop_index(op.f("ix_recording_sessions_user_id"), table_name="recording_sessions")
    op.drop_index(op.f("ix_recording_sessions_line_id"), table_name="recording_sessions")
    op.drop_geospatial_index(
        "idx_recording_sessions_computed_path",
        table_name="recording_sessions",
        postgresql_using="gist",
        column_name="computed_path",
    )
    op.drop_geospatial_table("recording_sessions")
    op.drop_index(op.f("ix_lines_submitted_by_id"), table_name="lines")
    op.drop_index(op.f("ix_lines_name"), table_name="lines")
    op.drop_table("lines")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
