"""initial

Revision ID: c0684faa5277
Revises: 
Create Date: 2026-03-15 15:08:19.751662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from geoalchemy2 import Geometry
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'c0684faa5277'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Ensure PostGIS extension is available
    op.execute('CREATE EXTENSION IF NOT EXISTS postgis')
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_geospatial_table('lines',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('path', Geometry(geometry_type='LINESTRING', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'MERGED', name='linestatus'), nullable=False),
    sa.Column('merged_into_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['merged_into_id'], ['lines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_lines_path', 'lines', ['path'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_lines_name'), 'lines', ['name'], unique=False)
    op.create_table('route_estimations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('line_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'SUPERSEDED', name='estimationstatus'), nullable=False),
    sa.Column('trip_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['line_id'], ['lines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_route_estimations_line_id'), 'route_estimations', ['line_id'], unique=False)
    op.create_geospatial_table('trip_sessions',
    sa.Column('line_id', sa.Uuid(), nullable=True),
    sa.Column('direction', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('device_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('device_model', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('os_version', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'ABANDONED', 'DISCARDED', name='sessionstatus'), nullable=False),
    sa.Column('processing_status', sa.Enum('RAW', 'PROCESSING', 'PROCESSED', 'FAILED', name='processingstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(), nullable=False),
    sa.Column('computed_path', Geometry(geometry_type='LINESTRING', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.ForeignKeyConstraint(['line_id'], ['lines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_trip_sessions_computed_path', 'trip_sessions', ['computed_path'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_trip_sessions_device_id'), 'trip_sessions', ['device_id'], unique=False)
    op.create_index(op.f('ix_trip_sessions_line_id'), 'trip_sessions', ['line_id'], unique=False)
    op.create_geospatial_table('route_segments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('estimation_id', sa.Uuid(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('path', Geometry(geometry_type='LINESTRING', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', name='segmentstatus'), nullable=False),
    sa.Column('votes_for', sa.Integer(), nullable=False),
    sa.Column('votes_against', sa.Integer(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['estimation_id'], ['route_estimations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_route_segments_path', 'route_segments', ['path'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_route_segments_estimation_id'), 'route_segments', ['estimation_id'], unique=False)
    op.create_table('trip_sensor_readings',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('accel_x', sa.Float(), nullable=True),
    sa.Column('accel_y', sa.Float(), nullable=True),
    sa.Column('accel_z', sa.Float(), nullable=True),
    sa.Column('gyro_x', sa.Float(), nullable=True),
    sa.Column('gyro_y', sa.Float(), nullable=True),
    sa.Column('gyro_z', sa.Float(), nullable=True),
    sa.Column('pressure', sa.Float(), nullable=True),
    sa.Column('magnetic_heading', sa.Float(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['trip_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trip_sensor_readings_session_id'), 'trip_sensor_readings', ['session_id'], unique=False)
    op.create_geospatial_table('trip_session_points',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('altitude', sa.Float(), nullable=True),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('bearing', sa.Float(), nullable=True),
    sa.Column('horizontal_accuracy', sa.Float(), nullable=True),
    sa.Column('vertical_accuracy', sa.Float(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('point', Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['trip_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_trip_session_points_point', 'trip_session_points', ['point'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_trip_session_points_session_id'), 'trip_session_points', ['session_id'], unique=False)
    op.create_geospatial_table('trips',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('line_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('CLEAN', 'DEVIATED', name='tripstatus'), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('frechet_distance', sa.Float(), nullable=True),
    sa.Column('computed_path', Geometry(geometry_type='LINESTRING', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['line_id'], ['lines.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['trip_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_trips_computed_path', 'trips', ['computed_path'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_trips_line_id'), 'trips', ['line_id'], unique=False)
    op.create_index(op.f('ix_trips_session_id'), 'trips', ['session_id'], unique=False)
    op.create_table('resampled_trips',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('trip_id', sa.Uuid(), nullable=False),
    sa.Column('interval_meters', sa.Float(), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=False),
    sa.Column('point_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resampled_trips_trip_id'), 'resampled_trips', ['trip_id'], unique=False)
    op.create_table('segment_votes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('segment_id', sa.Uuid(), nullable=False),
    sa.Column('trip_id', sa.Uuid(), nullable=False),
    sa.Column('vote', sa.Enum('APPROVE', 'REJECT', name='votechoice'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['segment_id'], ['route_segments.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_segment_votes_segment_id'), 'segment_votes', ['segment_id'], unique=False)
    op.create_index(op.f('ix_segment_votes_trip_id'), 'segment_votes', ['trip_id'], unique=False)
    op.create_table('travel_time_samples',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('trip_id', sa.Uuid(), nullable=False),
    sa.Column('segment_id', sa.Uuid(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('hour_of_day', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['segment_id'], ['route_segments.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_travel_time_samples_segment_id'), 'travel_time_samples', ['segment_id'], unique=False)
    op.create_index(op.f('ix_travel_time_samples_trip_id'), 'travel_time_samples', ['trip_id'], unique=False)
    op.create_geospatial_table('trip_points',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('trip_id', sa.Uuid(), nullable=False),
    sa.Column('point_index', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('point', Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_trip_points_point', 'trip_points', ['point'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_trip_points_trip_id'), 'trip_points', ['trip_id'], unique=False)
    op.create_geospatial_table('resampled_trip_points',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('resampled_trip_id', sa.Uuid(), nullable=False),
    sa.Column('point_index', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('point', Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.ForeignKeyConstraint(['resampled_trip_id'], ['resampled_trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_resampled_trip_points_point', 'resampled_trip_points', ['point'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_resampled_trip_points_resampled_trip_id'), 'resampled_trip_points', ['resampled_trip_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resampled_trip_points_resampled_trip_id'), table_name='resampled_trip_points')
    op.drop_geospatial_index('idx_resampled_trip_points_point', table_name='resampled_trip_points', postgresql_using='gist', column_name='point')
    op.drop_geospatial_table('resampled_trip_points')
    op.drop_index(op.f('ix_trip_points_trip_id'), table_name='trip_points')
    op.drop_geospatial_index('idx_trip_points_point', table_name='trip_points', postgresql_using='gist', column_name='point')
    op.drop_geospatial_table('trip_points')
    op.drop_index(op.f('ix_travel_time_samples_trip_id'), table_name='travel_time_samples')
    op.drop_index(op.f('ix_travel_time_samples_segment_id'), table_name='travel_time_samples')
    op.drop_table('travel_time_samples')
    op.drop_index(op.f('ix_segment_votes_trip_id'), table_name='segment_votes')
    op.drop_index(op.f('ix_segment_votes_segment_id'), table_name='segment_votes')
    op.drop_table('segment_votes')
    op.drop_index(op.f('ix_resampled_trips_trip_id'), table_name='resampled_trips')
    op.drop_table('resampled_trips')
    op.drop_index(op.f('ix_trips_session_id'), table_name='trips')
    op.drop_index(op.f('ix_trips_line_id'), table_name='trips')
    op.drop_geospatial_index('idx_trips_computed_path', table_name='trips', postgresql_using='gist', column_name='computed_path')
    op.drop_geospatial_table('trips')
    op.drop_index(op.f('ix_trip_session_points_session_id'), table_name='trip_session_points')
    op.drop_geospatial_index('idx_trip_session_points_point', table_name='trip_session_points', postgresql_using='gist', column_name='point')
    op.drop_geospatial_table('trip_session_points')
    op.drop_index(op.f('ix_trip_sensor_readings_session_id'), table_name='trip_sensor_readings')
    op.drop_table('trip_sensor_readings')
    op.drop_index(op.f('ix_route_segments_estimation_id'), table_name='route_segments')
    op.drop_geospatial_index('idx_route_segments_path', table_name='route_segments', postgresql_using='gist', column_name='path')
    op.drop_geospatial_table('route_segments')
    op.drop_index(op.f('ix_trip_sessions_line_id'), table_name='trip_sessions')
    op.drop_index(op.f('ix_trip_sessions_device_id'), table_name='trip_sessions')
    op.drop_geospatial_index('idx_trip_sessions_computed_path', table_name='trip_sessions', postgresql_using='gist', column_name='computed_path')
    op.drop_geospatial_table('trip_sessions')
    op.drop_index(op.f('ix_route_estimations_line_id'), table_name='route_estimations')
    op.drop_table('route_estimations')
    op.drop_index(op.f('ix_lines_name'), table_name='lines')
    op.drop_geospatial_index('idx_lines_path', table_name='lines', postgresql_using='gist', column_name='path')
    op.drop_geospatial_table('lines')
    op.execute('DROP TYPE IF EXISTS linestatus')
    op.execute('DROP TYPE IF EXISTS estimationstatus')
    op.execute('DROP TYPE IF EXISTS sessionstatus')
    op.execute('DROP TYPE IF EXISTS processingstatus')
    op.execute('DROP TYPE IF EXISTS segmentstatus')
    op.execute('DROP TYPE IF EXISTS tripstatus')
    op.execute('DROP TYPE IF EXISTS votechoice')
    # ### end Alembic commands ###
