[project]
name = "geodata-lab"
version = "0.1.0"
description = "Geodata Lab"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "geoalchemy2>=0.18.4",
    "pydeck>=0.9.1",
    "shapely>=2.0.0",
    "streamlit>=1.55.0",
    "watchdog>=6.0.0",
    "database>=0.1.0",
    "geodata>=0.1.0",
    "sqlalchemy>=2.0.48",
]

[tool.uv.sources]
database = {path = "../packages/database", editable = true}
